title: YueWu
logo: /assets/YueWu.png
description: Southern University of Science and Technology, B.S. Statistic
github: https://github.com/YueWu0301/YueWu0301/edit/main/_config.yml
show_downloads: False
theme: jekyll-theme-minimal